### ISSUE TITLE
Setting up SQL traces without tomcat-jdbc ?

### ISSUE THREAD

**Issue by christopheblin** [aws/aws-xray-sdk-java#103]
I'm using JDBI (jdbi.org) in a lambda with AWS Aurora.

I'd like to add traces for the SQL queries so I've read https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-sqlclients.html

I've added `compile 'com.amazonaws:aws-xray-recorder-sdk-sql-mysql:2.3.0'` in my bulid.gradle

However, when I use 'import org.apache.tomcat.jdbc.pool.DataSource;', it does not work

After looking in the poms, I see that tomcat-jdbc is declared as provided

However, I do not really want to include tomcat-jdbc in my lambda

So my question is : is there a way to trace SQL queries without tomcat-jdbc ?

**Comment by christopheblin** [comment]
I've managed to create my own solution based on successive proxy decoration of DataSource -> Connection > Statement that I have attached here (based on postgres and mySql exisitng TracingInterceptor.java)

However, there is something I can not understand about subsgement.putAllSql
```
Map<String, Object> additionalParams = new HashMap<>();
//some params skip for brevity
additionalParams.put("query", truncateSql(resolveExecutedSql(method.getName(), args)));
System.out.println("SQL " + truncateSql(resolveExecutedSql(method.getName(), args)));
Subsegment subsegment = AWSXRay.beginSubsegment("SQL");
subsegment.putAllSql(additionalParams);
```

Doing that, I correctly see my SQL in the Cloudwatch logs, however I can not see the "query" parameter in the SQL tab of the XRay trace. Can someone help here ?

[com.amazonaws.xray.sql.generic.zip](https://github.com/aws/aws-xray-sdk-java/files/3656524/com.amazonaws.xray.sql.generic.zip)

**Comment by christopheblin** [comment]
Please note that if I puth the query in driver_version with `additionalParams.put("driver_version", truncateSql(resolveExecutedSql(method.getName(), args)));`, then I can see the query in the XRay traces

So it indicates that there must be somewhere in the XRay server where the properties are checked (at least their names)

**Comment by christopheblin** [comment]
The correct key to put the sql is sanitized_query (I've had a look into python sdk and .net sdk)

Hope someone can have a look to my PR...

**Comment by chanchiem** [comment]
Thank you very much for the PR. We have added a few comments and really appreciate the contribution.  We think this is a great path forward to be able to support SQL generically and are extremely happy to work with you. Please let me know if you have any questions about the changes.

**Comment by shengxil** [comment]
Merged https://github.com/aws/aws-xray-sdk-java/pull/107
