### ISSUE TITLE
Open tracing support?

### ISSUE THREAD

**Issue by tosheer** [aws/aws-xray-sdk-java#11]
Are you guys planing to adhere to open tracing specification?

**Comment by haotianw465** [comment]
Hi, please see a response here: https://forums.aws.amazon.com/thread.jspa?threadID=272498&tstart=0
Will leave this issue open for a while for gathering more feedback from community.

**Comment by tosheer** [comment]
@haotianw465 Thanks mate. I have added more details on the forum question opened by me.

**Comment by ashleymercer** [comment]
@haotianw465 I've actually started building an xray-opentracing bridge internally for my current company, and I have a couple of questions:

- I'd be interested in open-sourcing this, and my company is supportive - would there be interest from you or from the community for this?

- if I do open-source, am I okay to refer to Amazon, AWS etc? I don't want to infringe on any copyright, and am very happy to make clear that I'm not affiliated with you guys in any way (other than being a very happy customer!)

Thanks

**Comment by dmytro-bekuzarov** [comment]
Hey guys. 
Can someone give the latest updates on the topic?
In particular, I am looking for either for java x-ray sdk compatible with AWS Java SDK v2 (which I suppose is not there yet) or for x-ray implementation of OpenTracing API in java (unofficial or whatever).
Willing to contribute, just don't want to start from scratch.

**Comment by ashleymercer** [comment]
Hi Dmytro :)

> java x-ray sdk compatible with AWS Java SDK v2 (which I suppose is not there yet)

Actually, it looks like they got around to adding X-Ray support to the SDK v2 in the last few weeks. I haven't tried it yet, but if you upgrade to version 2.2.1 of the Java SDK you should be set:

https://github.com/aws/aws-xray-sdk-java/blob/master/CHANGELOG.md

> or for x-ray implementation of OpenTracing API in java (unofficial or whatever).
> Wondering if it's even possible conceptually.

Actually, it is - although there are few inconsistencies in the API that you have to work around. As I mentioned above, we have a basic working version at my company except (a) it's currently written in Scala, so would need to be reworked in Java and (b) I haven't had time to open source it yet - but hopefully soon and will report back on this thread when it's done :)

Hope that helps,

Ashley

**Comment by dmytro-bekuzarov** [comment]
> Actually, it looks like they got around to adding X-Ray support to the SDK v2 in the last few weeks. I haven't tried it yet, but if you upgrade to version 2.2.1 of the Java SDK you should be set:
I tried, but it still relies on AWS SDK v1.x. Having an issue with it, posted here: https://github.com/aws/aws-xray-sdk-java/pull/56

> https://github.com/ashleymercer/opentracing-java-aws-xray
Waiting for updates :+1:

**Comment by ashleymercer** [comment]
Okay, after some back-and-forth with my company we've agreed to host this under a company organization on github. The first version of the code is here:

https://github.com/skylight-ipv/opentracing-java-aws-xray

@dmytro-bekuzarov if you get a chance, would you be able to try it out? I'm still figuring out signing and deployment to maven repos, so you'll need to build from scratch with maven 3.6.0 or higher.

@awssandra @haotianw465 would you be able to give the code an initial once-over? I think my broad approach is correct (just wrap the underlying `AWSXRayRecorder` and related classes in the OpenTracing API) but it might be better to provide a deeper integration?

**Comment by ashleymercer** [comment]
Update: this has now moved to live under the opentracing-contrib project:
https://github.com/opentracing-contrib/java-xray-tracer

**Comment by ashleymercer** [comment]
Just to keep this issue up to date: there is a move to unite two previous projects (OpenTracing, mentioned here, and a similar project called Open Census).

The combined, unified API will be called [OpenTelemetry](https://opentelemetry.io/about/) and the goal is to have the spec nailed down by the end of this year, I believe.

@tosheer @haotianw465 I'd like to propose updating this issue to "Native OpenTelemetry support".

**Comment by ss2305** [comment]
@ashleymercer We are currently working on something along the lines of "Native OpenTelemetry support" so it does make sense to updating this issue. Just out of curiosity, will you be contributing to the OpenTelemetry project emitters/bridges to work with X-Ray ?

**Comment by ashleymercer** [comment]
@ss2305 that would be awesome! Are you happy / able to update this existing issue, or is it worth creating a new one? Presumably this would be a new version (v3?) of the X-Ray libraries?

I'm not currently involved in OpenTelemetry directly, although I am on various mailing lists so trying to keep up with what's going on! If there are specific projects / repos you think I could help with, please point me in the right direction and I'll try to help where I can.

**Comment by willarmiros** [comment]
The X-Ray SDK has been implemented with the OpenTelemetry API standard in a [new repo](https://github.com/awslabs/aws-xray-sdk-with-opentelemetry). It will continue to be updated as the OpenTelemetry team updates their API [specification](https://github.com/open-telemetry/opentelemetry-java). Note that both the API specification, and with it our implementation, are in early, experimental stages. Please raise any issues with our integration on that repository. Thank you!
