### ISSUE TITLE
Missing "Host" header in HTTP request leads to exception been thrown.

### ISSUE THREAD

**Issue by thomas-gh** [aws/aws-xray-sdk-java#120]
Version: 2.4.0
Issue: LocalizedSamplingStrategy.java line108, see below 

`    firstApplicableRule = rules.stream().filter( rule -> rule.appliesTo(samplingRequest.getHost().get(), samplingRequest.getUrl().get(), samplingRequest.getMethod().get())).findFirst().orElse(null);`

throws a NoSuchElementException if Host header is absent in the request. MockMvc from Spring Framework doesn't supply Host header automatically, it means all of the controller test cases need to explicitly set Host header in order to pass the test.

A suggested solution is SamplingRequest.getHost() should return an empty string, instead of null, on the absence of Host header.

**Comment by shengxil** [comment]
Hello, by "all of the controller test cases need to explicitly set Host header in order to pass the test", which test is failing?

**Comment by thomas-gh** [comment]
> Hello, by "all of the controller test cases need to explicitly set Host header in order to pass the test", which test is failing?

All my test cases built with Spring MockMvc

**Comment by shengxil** [comment]
Hello, the bug is fixed by https://github.com/aws/aws-xray-sdk-java/commit/9d1a39d2350a9171fe118c6e7806a7941fa7795f. Closing
