### ISSUE TITLE
com.amazonaws.xray.sql.TracingStatement does not handle exceptions correctly.

### ISSUE THREAD

**Issue by chamsco-aws** [aws/aws-xray-sdk-java#136]
In the class `com.amazonaws.xray.sql.TracingStatement` if you do not have a current segment and your  `contextMissingStrategy` is set to something other than runtime error then in the following code in the section labeled `// don't trace if failed to create subsegment ` gets ran.

https://github.com/aws/aws-xray-sdk-java/blob/ec0c8ea869df3a5eb7716210a61ee6174b128b87/aws-xray-recorder-sdk-sql/src/main/java/com/amazonaws/xray/sql/TracingStatement.java#L98-L129

The issue is it does not have the same exception handling as the lower try/catch block with the comment `// the reflection may wrap the actual error with an InvocationTargetException...`, the first `if` block never tries to do `throw ite.getTargetException()` or `throw ite.getCause()` this causes a InvocationTargetException to be raised on a error.

The non-tracing path should have the same error unwrapping as the tracing path.

**Comment by shengxil** [comment]
Fix merged, closing
