### ISSUE TITLE
Support Spring Cloud AWS Messaging to use an SQS consumer as an X-Ray entry point to the service.

### ISSUE THREAD

**Issue by joodlehammond** [aws/aws-xray-sdk-java#163]
Hello!

One thing has become apparent to me while working with X-Ray, and that is that X-Ray expects the entry point for all services to be a REST controller of some sorts. The only way I have seen, so far, to create a segment is by using the servlet filter.

However, a lot of services, especially in my work place, have the entry point being an SQS consumer. Where the service polls SQS for messages, and on receipt of a message it starts processing it. Then once it is done processing, the service sends the processed message to another queue or another service.

```
@SqsConsumer("my-queue.fifo")
public void consumeMyQueueMessage(String message, Acknowledgement acknowlegement) {
    // consume
}
```
It would be great to be able to create a segment upon the receipt of a new message, and close the segment after acknowledging. Do you know if you guys have plans to implement this at all?

Also, if I have a go at this myself, may I create a pull request?

**Comment by joodlehammond** [comment]
I've just realized that i'm being silly, and this would be better to be implemented by the Spring Cloud guys, as you aren't directly related. Closing the issue.

**Comment by jakubgruber** [comment]
Hello @joodlehammond , did you manage to resolve the issue? If so, would you mind sharing the solution with me, please? I am trying to solve same problem.
