### ISSUE TITLE
java.lang.ClassCastException is thrown in version 2.7.0

### ISSUE THREAD

**Issue by gyurist** [aws/aws-xray-sdk-java#201]
After updating to version 2.7.0 we are seeing quite a few `java.lang.ClassCastException` errors in our logs:
```
java.lang.ClassCastException: class java.util.Collections$UnmodifiableMap cannot be cast to class java.util.HashMap (java.util.Collections$UnmodifiableMap and java.util.HashMap are in module java.base of loader 'bootstrap')
at com.amazonaws.xray.entities.SegmentImpl.setRuleName(SegmentImpl.java:152)
at com.amazonaws.xray.javax.servlet.AWSXRayServletFilter.preFilter(AWSXRayServletFilter.java:354)
at com.amazonaws.xray.javax.servlet.AWSXRayServletFilter.doFilter(AWSXRayServletFilter.java:185)
...
```

In `AWSXRayRecorder.java` the following initialisation is done:
https://github.com/aws/aws-xray-sdk-java/blob/38f038cac7b366865af6c73e4cb864b76cc4253a/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/AWSXRayRecorder.java#L111
https://github.com/aws/aws-xray-sdk-java/blob/38f038cac7b366865af6c73e4cb864b76cc4253a/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/AWSXRayRecorder.java#L166

And in `SegmentImpl.java` this value is attempted to be cast to a `HashMap` which throws an exception:
https://github.com/aws/aws-xray-sdk-java/blob/800131b31ba1c543ccb71aaecb1faff6f5c70055/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/entities/SegmentImpl.java#L152

**Comment by anuraaga** [comment]
Thanks for the report! This looks like several issues combining to finally create a bug. Will get a fix out soon.
