### ISSUE TITLE
subsegment name sanitization  

### ISSUE THREAD

**Issue by svetozar02** [aws/aws-xray-sdk-java#209]
According to https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html the name has following validation rules
`Names can contain Unicode letters, numbers, and whitespace, and the following symbols: _, ., :, /, %, &, #, =, +, \, -, @` 

It seems that this library is not actually validating the names. I'm getting `Message: "Invalid subsegment. ErrorCode: InvalidName, Cause: null"` in xray deamon because there are quite a few subsegment names that start with `$Proxy...` This is common in spring so I bet other people might run into similar issues

**Comment by srprash** [comment]
Hi @svetozar02 
You're right that the SDK doesn't validate the Segment/Subsegment names. This is because validating names through regex matching is performance expensive and we would like the SDK to be light weight. The X-Ray daemon serves as a proxy between the SDK and the service, and that's why you see the Invalid name error on the daemon logs.

**Comment by svetozar02** [comment]
From my perspective it would be better to remove unsupported characters and occur some performance hit than to fail silently. 

Anyways, resolved this by extending `BaseAbstractXRayInterceptor` and overriding `processXRayTrace` method. 
```
@Override
    protected Object processXRayTrace(ProceedingJoinPoint pjp) throws Throwable {
        try {
            var subsegmentName = pjp.getTarget().getClass().getSimpleName() + "." + pjp.getSignature().getName();
            subsegmentName = subsegmentName.replaceAll("[^\\w\\s_\\.:/%&#=+\\-@]", "");
            AWSXRay.beginSubsegment(subsegmentName);
            return XRayInterceptorUtils.conditionalProceed(pjp);
        } catch (Exception e) {
            AWSXRay.getCurrentSegmentOptional().ifPresent(x -> x.addException(e));
            throw e;
        } finally {
            AWSXRay.endSubsegment();
        }
    }
```

**Comment by srprash** [comment]
Yeah. I agree that we could do some processing on the segment name to remove the invalid characters but I also have some reservations about mutating the name provided/generated by the customer's application. This may lead to confusion when the customer tries to locate the traces with the segment name he might be expecting.
I'm glad that you were able to resolve this issue on your end. Unfortunately, we cannot provide a generic remedy for the issue. 
Thanks for your input.
