### ISSUE TITLE
how to transfer X-Amzn-Trace-Id to next request

### ISSUE THREAD

**Issue by Allen0710** [aws/aws-xray-sdk-java#21]
hello,boy
 I can not find where the X-Amzn-Trace-Id is put in httpServletRequest, can you tell me ,why?  how to transfer X-Amzn-Trace-Id to next request by the AWSXRayServletFilter

**Comment by luluzhao** [comment]
Hello @Allen0710 ,

Sorry for the late reply. For your first question, `X-Amzn-Trace-Id` is getting from [`upstream`](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/javax/servlet/AWSXRayServletFilter.java#L263). `X-Amzn-Trace-Id` is optional and pertains to continuing a trace vs starting one. If the header is missing on the request, this means that it is the start of a new trace. For your second question, we use `Segment` to pass trace header information to downstream calls. Take tracing AWS SDK call for example, after adding `TracingHandler` on your AWS SDK client, X-Ray SDK gets trace header information from [segment](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-aws-sdk/src/main/java/com/amazonaws/xray/handlers/TracingHandler.java#L164) and then [add](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-aws-sdk/src/main/java/com/amazonaws/xray/handlers/TracingHandler.java#L167) into next request which happens at `beforeRequest` handler function. Feel free to let me know if you have any other questions.

**Comment by haotianw465** [comment]
Closing. Please feel free to put additional comment here or open a new issue should any further help needed.
