### ISSUE TITLE
How to transfer X-Amzn-Trace-Id to next request by using the AWSXRayServletFilter

### ISSUE THREAD

**Issue by yanyan314** [aws/aws-xray-sdk-java#210]
The AWSXRayServletFilter will create segment when the application is up. How to transfer X-Amzn-Trace-Id to next request by using the AWSXRayServletFilter? can you give me an example?

**Comment by yanyan314** [comment]
Is that possible to calling this method "setTraceId(TraceID traceId)" after the segment is created by AWSXRayServletFilter?

**Comment by awssandra** [comment]
Hi yanyan314,

Traces represent a single request, and should not persist across multiple requests to the same web application. Trace IDs are also timestamped as a part of the format, so reusing them is not recommended.

Can you tell me a bit more about your usecase? Curious as to why you'd want to ruse the trace ID/parent/sampling decision present on the header.

Thanks,
Sandra
