### ISSUE TITLE
Instruction to instrument non-Spring applications using the SDKs.

### ISSUE THREAD

**Issue by bholagabbar-mt** [aws/aws-xray-sdk-java#22]
@zhengyal There are currently no instruction on how to implement tracing for non spring java applications. There is simply one line in the instructions that specifies https://github.com/aws/aws-xray-sdk-java#applications-not-using-javaxservlet-may-include-custom-interceptors-to-begin-and-end-trace-segments that * Applications not using javax.servlet may include custom interceptors to begin and end trace segments
Directly call beginSegment and endSegment as necessary. Note: this method requires additional work to ensure that the X-Amzn-Trace-Id header is properly propogated and sufficient information about the request and response is captured with the segment.* .

This seems like a very convenient way to leave the most important intricacies of tracing to the developer. Are there any guidelines on how we can implement this in our Java Play applications ?

**Comment by haotianw465** [comment]
Closing. Please feel free to put additional comments here or open a new issue should any further help needed.
