### ISSUE TITLE
Unable to trace deeper lambda Initialization segment

### ISSUE THREAD

**Issue by gustahrodrigues** [aws/aws-xray-sdk-java#226]
I'm following this AWS Lambda best practices:

>Take advantage of execution context reuse to improve the performance of your function. Initialize SDK clients and database connections outside of the function handler, and cache static assets locally in the /tmp directory. Subsequent invocations processed by the same instance of your function can reuse these resources. This saves execution time and cost. 
[AWS Docs](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html)

Based on this, on lambda's constructor, I'm reading secrets from Secrets Manager and make them available for `handleRequest()`, ie, I would like to read secrets only once. Also, I'm doing some other external resources initialization there.

Unfortunately, I'm not able to trace those using x-ray. When I try to trace it on `handleRequest()`, it worked properly. I know that lambda creates a default segment on each request, but I would like to trace lambda cold start too.

In x-ray console, I can see only one big segment called `Initialization`. How can I trace code inside lambda's constructor? How can I create a subsegment on `Initialization`?

```java
public class LambdaFunction implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {

    public LambdaFunction() {
        AWSXRay.beginSegment("lambda-constructor");
        readSecretsFromSecretsManager();
        //so some more initialization
        AWSXRay.endSegment();
    }

    @Override
    public APIGatewayProxyResponseEvent handleRequest(APIGatewayProxyRequestEvent input, Context context) {

       //use secrets and external resources

        return new APIGatewayProxyResponseEvent()
                .withBody("something")
                .withStatusCode(200);
    }

}
```

**Comment by lupengamzn** [comment]
Hey @gustahrodrigues ,

Thanks for the feedback

Currently Lambda only supports tracing the business logic of your application occurring in Lambda handler. That being said, right now there is no available option for you to create subsegments within `Initialization` that is created by Lambda.
