### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by anaynayak** [aws/aws-xray-sdk-java#23]
Hi,

I've been really looking forward to the changes done to DefaultOperationParameterWhitelist.json as part of https://github.com/aws/aws-xray-sdk-java/pull/9 which is currently in master but not part of a release. I didn't want to manage this file in my repository and hence was wondering when we could see a new release.

Thanks,
Anay

**Comment by awssandra** [comment]
Hi anaynayak,

I am sorry for the extended period you've been waiting for this change. We'll be doing a new release very shortly.

Thanks
Sandra

**Comment by anaynayak** [comment]
thanks for the update Sandra. Will wait for the release.

**Comment by anaynayak** [comment]
@awssandra is this going to take some time ?

**Comment by luluzhao** [comment]
@anaynayak , This feature released in 2.0.0.
