### ISSUE TITLE
ForcedSampling is not properly supported

### ISSUE THREAD

**Issue by friscoMad** [aws/aws-xray-sdk-java#230]
There is no way to enable ForcedSampling in any of the provided Strategies, we can extend our own strategy to enable it but it is far from ideal.
beginSegmentWithSampling does not take ForcedSampling into account, it is only supported by the servlet filter.
Ideally, the servlet filter should also support forcing sampling by status code (so for example all 500 errors are sampled).

**Comment by willarmiros** [comment]
Hi @friscoMad,

Thanks for raising the fact that ForcedSampling is not taken into account for `beginSegmentWithSampling`, I can address that bug. We can also add a new constructor parameter to enable ForcedSampling on our currently vended strategies. At this time we don't plan on releasing any official sampling strategies that use forced sampling directly, but you are always able to implement custom strategies for such use cases.
