### ISSUE TITLE
LogErrorContextMissingStrategy stack trace logging bug

### ISSUE THREAD

**Issue by friscoMad** [aws/aws-xray-sdk-java#234]
In #191 it was introduced a debug trace to show the stack trace when a context error was suppressed, it is really nice to find out places that neede to be corrected, except it is doesn't work as expected, this is the trace it produces:
`[LogErrorContextMissingStrategy] java.lang.RuntimeException: Failed to end subsegment: subsegment cannot be found.`

The throwable should be the second param and a message should be added as the first param, otherwise, Apache logging just calls toString on the first param to get the message.

**Comment by willarmiros** [comment]
Thanks for raising this @friscoMad, silly miss on my end.
