### ISSUE TITLE
Spring @Async XRay

### ISSUE THREAD

**Issue by nactusem** [aws/aws-xray-sdk-java#249]
Hi,
I have a structure like;

```
method(){
          asyncMethod();
          Entity segment = AWSXRay.getGlobalRecorder().getTraceEntity();
		Thread thread = new Thread() {
			@Override
            public void run() {
                if (segment != null) {
                    segment.run(() -> {
                        AWSXRay.beginSubsegment("## Report Building Thread");
                        startReportThreadExecution();
                        AWSXRay.endSubsegment();
                    });
                }else{
                    logger.debug("Segment not found, proceeding...");
                }
            }
    }
}

@Async
String asyncMethod(){
//do some stuff
}
```
While using xray I have a spring annotated Async method and a runnable code. I have managed to trace runnable code but in async method I lost the trace. How should I use xray in these methods? I passed traceEntity to async method and set it inside.
But most of the time it produces Segment already emitted exception.
Thanks in advance.

**Comment by willarmiros** [comment]
Hi @nactusem,

> But most of the time it produces Segment already emitted exception

This means that your thread is running (and creating the "Report Building Thread" subsegment) *after* the incoming request to your Spring app has been handled and the segment that represents that request is ended. Once that segment is ended and streamed to the X-Ray daemon, it cannot be modified or have additional subsegments added to it.

I'd suggest that you follow the first recommendation in the [multithreading docs](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-multithreading.html) and begin a new segment in your background thread, and attach the "Report Building Thread" subsegment to that instead.
