### ISSUE TITLE
Read _X_AMZN_TRACE_ID from system properties if environment variable is not set

### ISSUE THREAD

**Issue by Morras** [aws/aws-xray-sdk-java#251]
Using a custom Lambda runtime, you are required to set the _X_AMZN_TRACE_ID environment variable on each request.

In Java there is no easy way of setting environment variables at runtime, [this StackOverflow post](https://stackoverflow.com/questions/318239/how-do-i-set-environment-variables-from-java) details some of the hacks and edge cases you need to work around to get this to  work.

The Lambda custom runtime documentation clearly says this should be an environment variable, but would it be possible to create a fallback for the Java SDK, where in case the environment variable is not set, it will check the system properties?

The relevant SDK code is [line 40 in LambdaSegmentContext](https://github.com/aws/aws-xray-sdk-java/blob/636e980d392db88e8bdb6c2a2f9f358777c36b86/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/contexts/LambdaSegmentContext.java#L40). 

Having system properties as a fallback would still compatible with the documentation and any implementation using environment variables, but future Java implementations would not need to circumvent the environment variables system in Java.

**Comment by FieryCod** [comment]
@willarmiros Do you maybe know when this feature is gonna be published?

**Comment by bhautikpip** [comment]
Probably you can use the latest snapshot (https://aws.oss.sonatype.org/content/repositories/snapshots/) to consume this enhancement and that will unblock you temporararily while waiting for the actual release. We publish snapshot on every merge to `master` branch.

**Comment by smirnoal** [comment]
is this issue still relevant? has reading from system props logic landed any release?
