### ISSUE TITLE
Any other way to intercept requests for Aurora Postgresql rather than TracingInterceptor ?

### ISSUE THREAD

**Issue by swanandvk** [aws/aws-xray-sdk-java#253]
Is there any other recommended way to intercept JDBC calls ? 
which is similar to TracingInterceptor but it relies on connection pool for JDBC interceptor which 
is not readily available with PostgreSQL driver
https://github.com/aws/aws-xray-sdk-java/blob/67172dc861e785b8f8f230c7c6ba00aac562de71/aws-xray-recorder-sdk-sql-postgres/src/main/java/com/amazonaws/xray/sql/postgres/TracingInterceptor.java#L45

**Comment by willarmiros** [comment]
Hi @swanandvk,

We do have a generic SQL interception library (`aws-xray-recorder-sdk-sql`) which can decorate objects implementing JDBC interfaces. This package didn't get documented when merged, so I'll add it to the README, but you should be able to use it like this:

```
dataSource = TracingDataSource.decorate(dataSource);
connection = TracingConnection.decorate(connection);
statement = TracingStatement.decorateStatement(statement);
preparedStatement = TracingStatement.decoratePreparedStatement(preparedStatement, sql);
callableStatement = TracingStatement.decorate CallableStatement(callableStatement, sql);
```

You can also check out our [auto-instrumentation agent](https://github.com/aws/aws-xray-java-agent), which auto-instruments all JDBC-based SQL queries out of the box.

**Comment by swanandvk** [comment]
Thanks @willarmiros for the update 👍 
Hope [auto-instrumentation agent](https://github.com/aws/aws-xray-java-agent) works with Lambda as well

**Comment by willarmiros** [comment]
@swanandvk Unfortunately the agent is not supported on Lambda, and we do not have plans to add such support because of internal limitations of Lambda itself: https://github.com/aws/aws-xray-java-agent#compatibility-chart

You're probably better off just using the SDK's SQL library then :)

**Comment by swanandvk** [comment]
ok , thanks @willarmiros
