### ISSUE TITLE
SegmentContextExecutor doesn't have reference to currentSubsegment

### ISSUE THREAD

**Issue by dmccorm2** [aws/aws-xray-sdk-java#260]
Using aws-xray-recorder-sdk-core:2.8.0 for manual instrumentation, experienced/recreated issue locally on Java 8 inside a JUnit Test.

The issue I'm experiencing is the SegmentContextExecutor propagates the correct Segment to a CompletableFuture, but when I run AWSXRay.beginSubsegment() inside the entity.run() runnable, its parent is the current Segment, not the current Subsegment. Similarly, when I run AWSXRay.getCurrentSubsegment(), I receive an exception. 

When using a local debugger to troubleshoot I noticed the SegmentContextExecutor provides the current Trace Entity to my async function, but loses reference to the currentSubsegment, even executing inside the Entity Runnable: `AWSXray.getTraceEntity().run(...)`.

I can tell the segment is made available, since `AWSXray.getTraceEntity()` returns the correct Segment, however, if there's an ongoing Subsegment, I can't get a reference to it using `AWSXray.getCurrentSubsegment()`. I receive a `"com.amazonaws.xray.exceptions.SubsegmentNotFoundException: No subsegment in progress."` exception. However, when examining the Entity/segment in the debugger, I can see it has a Subsegment marked as in progress - both through inspection and `AWSXRay.getTraceEntity().getSubsegments().get(0).isInProgress()`.

The example below prints the exception I mentioned above.

```java
    @Test
    void testNativeCompletableFuture() {
        AWSXRay.beginSegment("Test"); 
        AWSXRay.beginSubsegment("Test Subsegment");
        try {
            CompletableFuture.runAsync(() -> AWSXRay.getTraceEntity().run(() -> AWSXRay.getCurrentSubsegment()), SegmentContextExecutors.newSegmentContextExecutor()).get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
        AWSXRay.endSubsegment();
        AWSXRay.endSegment();
    }
```

I would expect the currentSubsegment to be available when the referenced recorder is propagated to the executor, so when `AWSXRay.beginSubsegment()` is called inside the `entity.run()` runnable, its parent is the current subsegment.

**Comment by anuraaga** [comment]
Hi @dmccorm2 - yeah it seems like `SegmentContextExecutors` could have been just based on the current `Entity` instead of `Segment` which is causing your issue. I think the current workaround would be to treat the entity as an executor using a lambda

```java
    @Test
    void testNativeCompletableFuture() {
        AWSXRay.beginSegment("Test"); 
        AWSXRay.beginSubsegment("Test Subsegment");
        Entity entity = AWSXray.getTraceEntity();
        try {
            CompletableFuture.runAsync(() -> AWSXRay.getTraceEntity().run(() -> AWSXRay.getCurrentSubsegment()), entity::run).get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
        AWSXRay.endSubsegment();
        AWSXRay.endSegment();
    }
```

Is this a reasonable workaround for now? Going forward, we need to overhaul our context APIs as they're pretty confusing right now.
