### ISSUE TITLE
Failed to begin subsegment named 'AWSXRay'

### ISSUE THREAD

**Issue by steven-aerts** [aws/aws-xray-sdk-java#27]
When you use the `CentralizedSamplingStrategy` it will create a java sdk AWSXRay client which uses the XRay http api to communicate with the local xray daemon.
This client is used from a polling threads which typically do not have any context set.

When you have enabled the `aws-xray-recorder-sdk-aws-sdk-instrumentor` it will trigger the currently configured `ContextMissingStrategy` (throwing a runtime exception or logging an error).

We think this is rather ugly.

We are wondering if this is the designed behaviour.  

Wouldn't it be better to run these pollers within a dummy segment or disable the xray request handlers for the AWSXRay client?

**Comment by awssandra** [comment]
Hi Steven,

Sorry for the issue, this was not intended. The AWSXRay client requests to the new Centralized Sampling API should not be traced as they are not part of the application's request code path. We'll be investigating this and pushing a fix as soon as we can.

Closing in favor of tracking this issue on [#25](https://github.com/aws/aws-xray-sdk-java/issues/27)
