### ISSUE TITLE
Segment with a massive list of subsegments crashing on send in UDPEmiter

### ISSUE THREAD

**Issue by ygrenzinger** [aws/aws-xray-sdk-java#291]
Hello, 

I don't know where it's coming from but I keep having UDPEmitter sending too big message.

The exception looks like this:
```
level: ERROR
   logger: com.amazonaws.xray.emitters.UDPEmitter

   message: Exception while sending segment over UDP for entity sqs-newirp-individual-query [19df82e5f6b65a7e] on segment [no parent segment]

stackTrace: java.io.IOException: Message too long at j.n.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java) at 
j.net.DatagramSocket.send(DatagramSocket.java:695) at c.a.x.e.UDPEmitter.sendData(UDPEmitter.java:106) at 
c.a.x.e.UDPEmitter.sendSegment(UDPEmitter.java:84) at 
c.a.x.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:195) at 
c.a.x.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:588) at 
c.a.x.i.TracingInterceptor.afterExecution(TracingInterceptor.java:288) at 
s.a.a.c.i.ExecutionInterceptorChain.lambda$afterExecution$11(ExecutionInterceptorChain.java:192) at 
s.a.a.c.i.ExecutionInterceptorChain.reverseForEach(ExecutionInterceptorChain.java:234) at 
s.a.a.c.i.ExecutionInterceptorChain.afterExecution(ExecutionInterceptorChain.java:192) at 
s.a.a.c.i.h.p.s.AfterExecutionInterceptorsStage.execute(AfterExecutionInterceptorsStage.java:26) at 
s.a.a.c.i.h.p.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) at 
s.a.a.c.i.h.p.s.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) at 
s.a.a.c.i.h.p.s.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) at 
s.a.a.c.i.h.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) at 
s.a.a.c.i.h.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:135) at 
s.a.a.c.i.h.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:161) at 
s.a.a.c.i.h.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:114) at 
s.a.a.c.i.h.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:169) at 
s.a.a.c.i.h.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:95) at 
s.a.a.c.c.h.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) at

 s.a.a.a.c.h.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55) at 
s.a.a.s.s.DefaultSqsClient.getQueueUrl(DefaultSqsClient.java:859) at 
c.e.n.p.i.a.s.c.c.h.i.QueueHealthIndicator.checkQueue(QueueHealthIndicator.java:51) at 
j.u.s.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) at 
j.u.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) at 
j.u.s.AbstractPipeline.copyInto(AbstractPipeline.java:484) at 
j.u.s.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at 
j.u.s.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) at j.u.s.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) 
at j.u.s.AbstractTask.compute(AbstractTask.java:327) at j.u.c.CountedCompleter.exec(CountedCompleter.java:746) at 
j.u.c.ForkJoinTask.doExec(ForkJoinTask.java:290) at j.u.c.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) 
at j.u.c.ForkJoinPool.scan(ForkJoinPool.java:1656) at j.u.c.ForkJoinPool.runWorker(ForkJoinPool.java:1594) at 
j.u.c.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I logged the segment.prettySerialize in UDPEmiter and it seems like there is only one segment with every next trace appended as a subsegment :o

It's on Java 11 with these versions of the SDK :
`    <aws-java-sdk-bom.version>1.12.27</aws-java-sdk-bom.version>
    <aws-java-sdkv2-bom.version>2.16.104</aws-java-sdkv2-bom.version>
    <aws-xray-recorder-sdk-bom.version>2.9.0</aws-xray-recorder-sdk-bom.version>`

If you have any idea to help me understanding where it's coming from :)

**Comment by willarmiros** [comment]
Hi @ygrenzinger,

The maximum size that can be streamed out by the UDP emitter at once is 64 kB. By default, the SDK will wait until there are 100 subsegments to start attempting to stream them. However if they are deeply nested, this can force the SDK to wait even longer. If you have a very large amount of subsegments, I suggest setting the streaming threshold to lower values, such as 20. You can continue to decrease the value until you no longer experience this error.

```java
AWSXRay.setGlobalRecorder(AWSXRayRecorderBuilder.standard().withStreamingStrategy(new DefaultStreamingStrategy(20)).build());
```

Also in general, the max size for a trace is 500 kB, so no matter what that limit cannot be exceeded.

**Comment by ygrenzinger** [comment]
I have put 0 in the DefaultStreamingStrategy. It's more like it keeps adding subsegment to the same segment. I will try to localize more precisely the problem with a colleague on next week.

**Comment by ygrenzinger** [comment]
Hello,

I am waiting to have the luck to reproduce it in local for debug but more context on the error with logs:

| Date| Level | Message |
| :-- | :-- | :-- |
| 2021-07-30T12:57:42.118Z | ERROR | Exception while sending segment over UDP for entity sqs-uat-newirp-individual-query [**1f6b517d7fa48c78**] on segment [no parent segment] |
| 2021-07-30T12:57:42.110Z | ERROR | Exception while sending segment over UDP for entity sqs-uat-individual-query [**1f6b517d7fa48c78**] on segment [no parent segment] |
| 2021-07-30T12:57:42.101Z | ERROR | Exception while sending segment over UDP for entity sqs-uat-individual-query [**1f6b517d7fa48c78**] on segment [no parent segment] |
| 2021-07-30T12:51:20.656Z | DEBUG | Ending segment {"name":"sqs-uat-individual-query-response-notification","id":"405654cc3b489687","parent_id":"**1f6b517d7fa48c78**","start_time":1.627649480007E9,"trace_id":"1-6103f5c0-75d8d04904a6737f63cb6387","in_progress":true,"aws":{"xray":{"sdk_version":"2.9.0","sdk":"X-Ray  for Java"}},"service":{"runtime_version":"11.0.12","runtime":"OpenJDK 64-Bit Server VM"}} |
| 2021-07-30T12:51:20.007Z | DEBUG | Starting segment with tracingName=sqs-uat-individual-query-response-notification traceId=1-6103f5c0-75d8d04904a6737f63cb6387 parentId=1f6b517d7fa48c78
| 2021-07-30T12:51:18.379Z | DEBUG | Ending segment {"name":"sqs-uat-individual-query","id":"**1f6b517d7fa48c78**","parent_id":"0ba242f38eeadd26","start_time":1.627649472519E9,"trace_id":"1-6103f5c0-75d8d04904a6737f63cb6387","in_progress":true,"aws":{"xray":{"sdk_version":"2.9.0","sdk":"X-Ray  for Java"}},"service":{"runtime_version":"11.0.12","runtime":"OpenJDK 64-Bit Server VM"}} |

The send segment error happens when the TracingExecutor around GetQueueUrl generate the trace and try to send it. We use the QueueUrl SDK API to regularly check if the queue is alive.

What we can see in the previous table of logs is that is keeps reusing the id **1f6b517d7fa48c78** for an unknow reason ... 

Another information, I tried to display the segment before UDPEmitter sends it and there is a ultra long (so long I can't display it) repetition of something similar to this : `{\n          \"retries\" : 0,\n          \"region\" : \"eu-central-1\",\n          \"operation\" : \"GetQueueUrl\",\n          \"request_id\" : \"27895dc3-26a2-5c96-a1dd-04bf6bf073e8\"\n        }\n      }`

Again if there is some intuition around the problem :)

BTW another would be to filter the tracing of AWS SDK call but I don't how to configure xray tracing to do this.

**Comment by willarmiros** [comment]
> Another information, I tried to display the segment before UDPEmitter sends it and there is a ultra long (so long I can't display it) repetition of something similar to this

This would mean that you are making several requests (as many requests as there are subsegments) to `GetQueueUrl`. Are you intending to make that many requests? 

> BTW another would be to filter the tracing of AWS SDK call but I don't how to configure xray tracing to do this

I agree this would be the best immediate workaround. How are you instrumenting your SQS client currently? Please take a look at our guide on instrumenting individual AWS SDK clients, so perhaps you could cease instrumenting the SQS client while instrumenting the others: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-awssdkclients.html

**Comment by ygrenzinger** [comment]
Hello,

an update of version dependancies seems to have fixed the problem so far:
    <aws-java-sdk-bom.version>1.12.40</aws-java-sdk-bom.version>
    <aws-java-sdkv2-bom.version>2.17.14</aws-java-sdkv2-bom.version>
    <aws-xray-recorder-sdk-bom.version>2.9.1</aws-xray-recorder-sdk-bom.version>
_instead of_
    <aws-java-sdk-bom.version>1.12.27</aws-java-sdk-bom.version>
    <aws-java-sdkv2-bom.version>2.16.104</aws-java-sdkv2-bom.version>
    <aws-xray-recorder-sdk-bom.version>2.9.0</aws-xray-recorder-sdk-bom.version>
