### ISSUE TITLE
Add "Automatic-Module-Name" to JAR Manifest

### ISSUE THREAD

**Issue by brcolow** [aws/aws-xray-sdk-java#292]
Currently when trying to use `aws-xray-sdk-java` on a modular Java project one gets the following error:

```
 (package com.amazonaws.xray.interceptors is declared in the unnamed module, but module my.module does not read it)
```

Even though this project is not modular you can use the `Automatic-Module-Name` fallback. Please see:

http://branchandbound.net/blog/java/2017/12/automatic-module-name/

Here is how it is used in AWS `aws-sdk-java-v2`, for example: https://github.com/aws/aws-sdk-java-v2/search?q=Automatic-Module-Name

Thank you.

**Comment by willarmiros** [comment]
Hi @brcolow,
I think we'd be open to adding this to support consumers that have modular java projects. If you're able to submit a PR to add this annotation we'd happily take a look!

**Comment by brcolow** [comment]
Thanks for getting back to me so quickly. Here is the pull request: https://github.com/aws/aws-xray-sdk-java/pull/295
