### ISSUE TITLE
SegmentNotFoundException: No segment in progress.

### ISSUE THREAD

**Issue by lishenwp** [aws/aws-xray-sdk-java#300]
Hi,

I have been trying to onboard X-Ray for our Java Spring-Boot web app.
I have followed the SDK guides to enable, for example:
WebConfig.
```
@Component
@Configuration
public class WebConfig {
    @Bean
    public Filter tracingFilter() {
        return new AWSXRayServletFilter("APP");
    }

    @Bean
    public AWSXRayRecorder awsxRayRecorder() {
        return AWSXRay.getGlobalRecorder();
    }

    static {
        AWSXRayRecorderBuilder builder = AWSXRayRecorderBuilder.standard().withPlugin(new ECSPlugin());

        URL ruleFile = WebConfig.class.getResource("sampling-rules.json");
        builder.withSamplingStrategy(new LocalizedSamplingStrategy(ruleFile));

        AWSXRay.setGlobalRecorder(builder.build());
    }
}
```

docker-compose setting
```
  local-xray:
    container_name: local-xray-1
    image: "amazon/aws-xray-daemon"
    command: --region us-west-2 --local-mode --log-level dev
```

I ran my containers locally with localstack.
But it seems like there are no segment created when requests come in, while the only evidence I could find that the SDK is doing something is I could find the X-Amzn-Trace-Id in my responses
<img width="733" alt="Screen Shot 2021-09-17 at 10 05 10 AM" src="https://user-images.githubusercontent.com/90925940/133826964-67472f37-5de7-47d1-955b-83d9d7a6658a.png">
.

Below are what I have tried:

  | Iterations | Result | X-Amzn-Trace-Id in Header?
-- | -- | -- | --
Tools |   |   |  
  |   |   |  
SDK | WebConfig Only | Nothing happened, Skipped telemetry data as no segments found | Yes
  | AWSXRay.beginSegment() | SegmentNotFoundException: No segment in progress. | Yes
  | AWSXRay.beguneSubsegment() | SegmentNotFoundException: No segment in progress. | Yes
  | Entity.Run() | SegmentNotFoundException: No segment in progress. | Yes
AOP | @Aspect XRayInspector | instantiation of bean failed | Yes
disco Agent | JVM Arg -javaagent:/<path-to-disco>/disco-java-agent.jar=pluginPath=/<path-to-disco>/disco-plugins | Nothing happened,  Skipped telemetry data as no segments found  | No

Does anyone experienced something similar? Was there any extra steps needed other than the ones in AWS.doc?
Thanks, logs below:
```
 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]
  - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
app-docker | com.amazonaws.xray.exceptions.SegmentNotFoundException: No segment in progress.
```

**Comment by willarmiros** [comment]
Hi @lishenwp,

This exception can be raised when your application attempts to make an instrumented call (such as a downstream HTTP or AWS SDK request) but there is no active segment context (typically because it is outside of the standard Spring route path handling). You can suppress this error by setting the environment variable `AWS_XRAY_CONTEXT_MISSING=IGNORE_ERROR`.

Alternatively, you can try a less invasive instrumentation with the newly generally available AWS Distro for OpenTelemetry Java auto-instrumentation agent, which shouln't throw such an error. You can see the [getting started guide here](https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr).

**Comment by lishenwp** [comment]
@willarmiros 
Thank you, will check that one. Regarding this specific issue, it was also resolved by not placing AWSXRay.endSegment() everywhere. Also set the logging level to DEBUG is also essential to see any SDK action(which was missed as I was relying on sl4j2 only). The app is deployed and tested working. Issue can be closed.
