### ISSUE TITLE
Lambda and HTTP API Gateway do not use same Trace-ID

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws/aws-xray-sdk-java#301]
Hi,
I am trying to get end to end tracing work for our setup.

We have HTTP-API-Gateway thats attached to a Lambda-Authorizer.
After requests are authorized, they make it to backend service deployed in Fargate.

Request making through API-GW gets `X-Amzn-Trace-Id` header attached to it. Based on [doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html), HTTP API-GW API is not supporting X-Ray. And We don't have any X-Ray specific config in AWS::ApiGatewayV2::* resources in our template. The Lambda had active tracing disabled to ensure its not adding it either. Why does API-GW add this header in this case?

When Active tracing is enabled in Lambda,
`_X_AMZN_TRACE_ID` trace id does not match what's being generated by API-GW. Even if we pass our own trace header as `X-Amzn-Trace-Id=root-****`, Lamda still does not use the trace header being passed.
This results in our service graph being split into two parts: `client->lambda` and `client->svc`.

How can we make Lambda pick up the trace id
 - Either the root-*** trace id passed from client 
 - OR traceId generated by API-GW ?

**Comment by willarmiros** [comment]
Hi @gautam-nutalapati,

Thanks for raising this issue. Can you try passing in a complete trace header (with the `parent` and `sampled` fields filled in too) to the Lambda to see if the issue persists? Lambda needs a full trace header to propagate context usually.

**Comment by gautam-nutalapati** [comment]
Hi, Sorry for delayed response. 
I am sending request from client that goes through HTTP APIGW > Lambda Authorizer -> ECS. 
For request is directly coming from a client, I am not sure if parent is applicable in traceId but I did send `X-Amzn-Trace-Id` header with value `Root=1-61607282-e1219b8660617cb5eb75761b;Parent=53995c3f42cd8ad8;Sampled=1`

X-Ray logs contain `"_X_AMZN_TRACE_ID": "Root\u003d1-616071f0-32751da4348974e8466444ba;Parent\u003da71a1a1f38a40832;Sampled\u003d1",` which doesn't match the header I passed in request.

Headers from request are logged and I see header I passed in `"X-Amzn-Trace-Id": "Self\u003d1-616071f0-67a9683721a3e1cb7e846897;Root\u003d1-616071e3-90f25409377689ade53ad4fd;Parent\u003d53995c3f42cd8ad8;Sampled\u003d1"`

**Comment by gautam-nutalapati** [comment]
After experimenting further, I think I will wait until HTTP API-GW starts supporting X-Ray. HTTP API-GW currently doesn't support X-Rayas per [this doc](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-apigateway.html)
Once HTTP PAI-GW support is added, we will see API-GW using common parent in XRay trace ID. (So that lambda authorizer and backend service traces come from same parent node as shown in [this](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-using-xray-maps.html) example for REST API GW )
Closing this issue.
