### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kjhok1811** [aws/aws-xray-sdk-java#328]

**Comment by wangzlei** [comment]
XRay SDK does not support spring webclient. There is solution in opentelemetry and [spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/blob/c795675cf93c666c3c13f9bbb9eadbde1f1aa775/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceExchangeFilterFunction.java#L67). We suggest user migrate to opentelemetry if using new frameworks.

**Comment by kjhok1811** [comment]
.
