### ISSUE TITLE
because Subsegment  too long   then trace log daemonSocket.send  error

### ISSUE THREAD

**Issue by feizhangyong** [aws/aws-xray-sdk-java#370]
when file download 
　Subsegment is  too long
　daemonSocket.send  error 

→　I want to fix it
![image](https://user-images.githubusercontent.com/85141881/217710866-88439546-9e50-4598-9866-165feea58812.png)

then error  is fixed
→ db trace logs are nothing
![image](https://user-images.githubusercontent.com/85141881/217711065-89f978cb-5167-466e-a916-2e78027e3d89.png)

**Comment by willarmiros** [comment]
Hi @feizhangyong - feel free to submit a PR if you have a fix for this issue ready!

**Comment by feizhangyong** [comment]
sorry ,not fix it
①BatchBaseApplication.java
   AWSXRayRecorderBuilder builder = AWSXRayRecorderBuilder.standard().withDefaultPlugins().withSamplingStrategy(new 
   NoSamplingStrategy()).withSegmentListener(new SLF4JSegmentListener());

②log is too long ,so i change the log
![image](https://user-images.githubusercontent.com/85141881/220015221-b745edb5-34e8-470f-9a67-303d5988df27.png)

these log are changed, sizes are ok


③after endSegment,
   segment.subsegmentsList　sizes also be too long
why?

**Comment by feizhangyong** [comment]
trace map and trace logs can be see,

The log (too long) part is not output to trace log

**Comment by willarmiros** [comment]
If you are getting subsegment too long errors, it is likely because the metadata you are adding is too big to fit into a UDP socket which is 64 KB. I would suggest removing or trimming the metadata you're adding to be less than 64 kB.

**Comment by feizhangyong** [comment]
thank you
control →service → logic　
parent     son          grandson


add this, Asserting Parent-Child Relationships of Classes

    @Override
    protected Object processXRayTrace(ProceedingJoinPoint pjp) throws Throwable {
    	Subsegment subsegment = AWSXRay.beginSubsegment(pjp.getSignature().getDeclaringTypeName() + "." + pjp.getSignature().getName());
    	**subsegment.setParentId(subsegment.getParentSegment().getId());**


UDPEmitter overwrite it
 loop Subsegment, 
             Iterator<Subsegment> iterator = subsegment.getSubsegments().iterator();
            while (iterator.hasNext()) {
                Subsegment childSubsegment = iterator.next();
                sendSubsegment(childSubsegment);
                iterator.remove();

→After the top-level response is completed, it is possible to resolve this issue.

**Comment by feizhangyong** [comment]
message too long 
are fixed 
should i need to post a pullrequest to overwrite UDPEmitter   ?

**Comment by feizhangyong** [comment]
> 

thank you ,

**Comment by willarmiros** [comment]
No need for a PR here - glad the issue was resolved!
