### ISSUE TITLE
Remove unnecessary Guava dependency

### ISSUE THREAD

**Issue by Sandmania** [aws/aws-xray-sdk-java#39]
In commit [Support CS in Java](https://github.com/aws/aws-xray-sdk-java/commit/c2b8c489f7370c1b322678a802abf7db0d1aa70f#diff-1f6986f2ee36e4237333e62419b4c7a3) `com.google.guava:guava:25.1-jre` was added as a dependency to aws-xray-recorder-sdk-core/pom.xml. To the best of my knowledge this is not used anywhere (all tests pass without it) and unnecessarily bloats up modules that depend on aws-xray-recorder-sdk-core. This can have adverse performance impacts in places like lambda deployments.

For the time being, I've manually excluded the dependency like so:

```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-xray-recorder-sdk-aws-sdk</artifactId>
            <version>2.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-xray-recorder-sdk-aws-sdk-instrumentor</artifactId>
            <version>2.0.1</version>
        </dependency>
```

X-Ray instrumentation seems to work as expected even without guava. Please let me know if excluding this dependency might lead into some unwanted results.

**Comment by haotianw465** [comment]
This issue is fixed as part of `2.1.0` release. See [CHANGELOG](https://github.com/aws/aws-xray-sdk-java/blob/master/CHANGELOG.md) for details.
