### ISSUE TITLE
Using com.amazonaws.xray.emitters.daemonAddress doesn't set TCPAddress and UDPAddress 

### ISSUE THREAD

**Issue by bh213** [aws/aws-xray-sdk-java#40]
Setting com.amazonaws.xray.emitters.daemonAddress doesn't set TCPAddress and UDPAddress properties in code here:

https://github.com/aws/aws-xray-sdk-java/blob/4034a834f0c580c9f661d096028f9bc654843aff/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/config/DaemonConfiguration.java#L46

and that causes null pointer exception here:
https://github.com/aws/aws-xray-sdk-java/blob/901f2f93cfcfabf43bbbb61f74f076c9158f1bac/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/sampling/XRayClient.java#L26

Now, I might be doing something wrong but it seems TCPAddress and UDPAddress  are not set when property is set. They are, however, set when environment variable is used or when there is no property or env variable.

thanks,
gorazd

**Comment by haotianw465** [comment]
Thanks for reporting the issue. We will look into a fix soon.

**Comment by haotianw465** [comment]
This issue is fixed as part of `2.1.0` release. See [CHANGELOG](https://github.com/aws/aws-xray-sdk-java/blob/master/CHANGELOG.md) for details.
