### ISSUE TITLE
Add and document X-Ray tracing for AWS SDK v2

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-xray-sdk-java#43]
## Expected Behavior

The AWS SDK team has now released [version 2](https://github.com/aws/aws-sdk-java-v2) of the Java SDK. Previously it was possible to write:

```java
AWSLambda lambda = AWSLambdaClientBuilder
      .standard()
      .withRequestHandlers(new TracingHandler(recorder))
      .build()
```

but the `RequestHandler` API has been replaced in v2 with a new `ExecutionInterceptor` API for wrapping client requests:

https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptor.java

This means that, as far as I can see, it's currently not possible to add X-Ray traces to AWS calls using the v2 SDK.

## Current Behavior

I can't see an equivalent implementation in the v2 SDK anywhere - assuming it would use the new `ExecutionInterceptor` API - or if there is one, I can't see it documented in [the developer guide](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html).

## Possible Solution
Add and document an implementation of `ExecutionInterceptor` that traces AWS client requests.

## Steps to Reproduce (for bugs)
N/A

## Context
Required for parity with the 1.11 SDK.

## Your Environment
* AWS Java SDK version used: 2.1.0
* JDK version used: 8

**Comment by awssandra** [comment]
Hi ashleymercer,

We are aware of the current issues and are actively working with the AWS SDK team to support X-Ray. We plan to have official support soon. Thank you for your patience, and stay tuned.

Thanks,
Sandra

**Comment by haotianw465** [comment]
AWS SDK for Java V2 is supported in 2.2.x. You can see the usage guide at the bottom of https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java.html. We are working on improving the docs. Feel free to put extra feedback for the doc.
