### ISSUE TITLE
Remove hard coded spring data dependency from com.amazonaws.xray.spring.aop.AbstractXRayInterceptor class, Project is not usable for non spring-data-jpa application 

### ISSUE THREAD

**Issue by ssrinivasulu** [aws/aws-xray-sdk-java#45]
Below code in AbstractXRayInterceptor is introducing spring-data-jpa library dependency and causing the library not to be used without adding "spring-data-jpa" the library to the project.  

    @Pointcut("execution(public !void org.springframework.data.repository.Repository+.*(..))")
    protected void springRepositories() {
    }

**Comment by luluzhao** [comment]
Hello @ssrinivasulu , sorry for the late response. Here I want to confirm that the issue you are currently facing caused by our `pom.xml` file doesn't have `spring-data-jpa` jar included, is that correct?

**Comment by ssrinivasulu** [comment]
Yes, that's correct. I would remove the dependency from code instead of adding the spring-data-jpa jar file to the aws-xray-sdk-java.

**Comment by tmuldoon** [comment]
I've also run into this issue. 

We don't use spring-data-jpa and as such, we cannot seem to use the AbstractXRayInterceptor class, given the Pointcut reference...
```
    @Pointcut("execution(public !void org.springframework.data.repository.Repository+.*(..))")
    protected void springRepositories() {
    }
```
... results in the following exception...
```
java.lang.IllegalArgumentException: warning no match for this type name: org.springframework.data.repository.Repository [Xlint:invalidAbsoluteTypeName]
```

**Comment by eric-swann-q2** [comment]
👆 Same here

**Comment by saki95** [comment]
I have the same issue . Could anybody provide me with the solution . thanks

**Comment by kgrodzicki** [comment]
> I have the same issue . Could anybody provide me with the solution . thanks

We have just copied 'AbstractXRayInterceptor' into project, deleted the @Pointcut("execution(public !void org.springframework.data.repository.Repository+.*(..))") and used this class as a base for XRayInterceptor. And it works like a charm, hope this helps.

XRayInterceptor:
`
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.stereotype.Component;

@Aspect
@Component
public class XRayInterceptor extends AbstractLeanXRayInterceptor {

    @Override
    @Pointcut("@within(com.amazonaws.xray.spring.aop.XRayEnabled)")
    public void xrayEnabledClasses() {
        // this defines which classes are enriched with X-Ray
    }

}

`

**Comment by zxkane** [comment]
> > I have the same issue . Could anybody provide me with the solution . thanks
> 
> @eric-swann-q2 @saki95 :
> We have copied 'AbstractXRayInterceptor' into the project, deleted the @pointcut("execution(public !void org.springframework.data.repository.Repository+.*(..))") and used this class as a base for XRayInterceptor. And it works like a charm, hope this helps.
> 
> XRayInterceptor:
> 
> ```
> import org.aspectj.lang.annotation.Aspect;
> import org.aspectj.lang.annotation.Pointcut;
> import org.springframework.stereotype.Component;
> 
> @Aspect
> @Component
> public class XRayInterceptor extends AbstractLeanXRayInterceptor {
> 
>     @Override
>     @Pointcut("@within(com.amazonaws.xray.spring.aop.XRayEnabled)")
>     public void xrayEnabledClasses() {
>         // this defines which classes are enriched with X-Ray
>     }
> 
> }
> ```

I tried it. But it does not work.

**Comment by zxkane** [comment]
+1, It's a really annoying and long living issue of enabling x-ray for spring application without using spring-data!

Team, pls assign proper dev to work on it.

**Comment by awssandra** [comment]
Hey all,

We will try and address this as soon as we can. Sorry for the delay!

Sandra

**Comment by shengxil** [comment]
https://github.com/aws/aws-xray-sdk-java/commit/cc6d6b9e5bcdac7cfe65a571a6ca62fda9a0bd5a is a workaround. Now you can safely use BaseAbstractXRayInterceptor without Spring jpa
