### ISSUE TITLE
Race Condition on configuring custom recorder for X-Ray servlet filter

### ISSUE THREAD

**Issue by haotianw465** [aws/aws-xray-sdk-java#51]
The `AWSXRayServletFilter` has multiple constructors that don't take a recorder as an input:https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/javax/servlet/AWSXRayServletFilter.java#L50-L60. In that case it will use the default global recorder initialized statically.

If the user create a custom recorder and set it to be the global one using `AWSXRay.setGlobalRecorder` after filter construction, this global recorder will not be used.

The servlet filter should not use any recorder if not passed during construction. It should lazy fetch the global recorder when the recorder is actually needed.

**Comment by chrisradek** [comment]
Closing as this was fixed in version 2.2.x of the SDK.
