### ISSUE TITLE
ClassCastException in Xray Java SDK when used with Lambda in Java Container using SpringBoot 

### ISSUE THREAD

**Issue by dhawalkp** [aws/aws-xray-sdk-java#55]
Scenario:
1. Create a RESTful API using Java Spring Boot in Lambda using 
<dependency>
    <groupId>com.amazonaws.serverless</groupId>
    <artifactId>aws-serverless-java-container-spring</artifactId>
    <version>1.3</version>
</dependency>
as per the instructions given in https://github.com/awslabs/aws-serverless-java-container

2. Add XRay Java SDK in Dependency as below
<dependency>
  <groupId>com.amazonaws</groupId>
  <artifactId>aws-xray-recorder-sdk-core</artifactId>
  <version>1.2.1</version>
</dependency>

<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-xray-recorder-sdk-apache-http</artifactId>
    <version>2.1.0</version>
</dependency>

3. Use  com.amazonaws.xray.proxies.apache.http.HttpClientBuilder class to create an httpClient to call external REST calls from this lambda so that Xray can intercept and add Subsegment ID to this outgoing call for overall tracing.

4. Expose the Lambda function using Lambda Proxy INtegration using API Gateway 
5. Test it using API Gateway Test Console
6. Get below error

2019-01-19T07:03:03.055Z java.lang.ClassCastException: com.amazonaws.xray.entities.SegmentImpl cannot be cast to com.amazonaws.xray.entities.Subsegment

2019-01-19T07:03:03.055Z 	at com.amazonaws.xray.contexts.LambdaSegmentContext.beginSubsegment(LambdaSegmentContext.java:53)

2019-01-19T07:03:03.055Z 	at com.amazonaws.xray.AWSXRayRecorder.beginSubsegment(AWSXRayRecorder.java:423)

2019-01-19T07:03:03.055Z 	at com.amazonaws.xray.proxies.apache.http.TracedHttpClient.execute(TracedHttpClient.java:171)

2019-01-19T07:03:03.055Z 	at com.amazon.sa.USCISCaseStatusController.caseStatus(USCISCaseStatusController.java:81)

2019-01-19T07:03:03.055Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2019-01-19T07:03:03.055Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2019-01-19T07:03:03.055Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2019-01-19T07:03:03.055Z 	at java.lang.reflect.Method.invoke(Method.java:498)

2019-01-19T07:03:03.055Z 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)

2019-01-19T07:03:03.055Z 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)

2019-01-19T07:03:03.055Z 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)

2019-01-19T07:03:03.055Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)

2019-01-19T07:03:03.055Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)

2019-01-19T07:03:03.056Z 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

2019-01-19T07:03:03.056Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)

2019-01-19T07:03:03.056Z 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)

2019-01-19T07:03:03.056Z 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)

2019-01-19T07:03:03.056Z 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)

2019-01-19T07:03:03.056Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

2019-01-19T07:03:03.056Z 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)

**Comment by chrisradek** [comment]
@dhawalkp 
Just to confirm, is your http client the only thing instrumented in your code to generate data for xray?

**Comment by chrisradek** [comment]
@dhawalkp 
I haven't been able to reproduce the issue you're seeing.

I created a Lambda function using the instructions from aws-serverless-java-container-spring like you linked to. Also using version 1.3.

Here's my pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cjr.sample</groupId>
    <artifactId>serverless-spring-boot</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Serverless Spring Boot API</name>
    <url>https://github.com/awslabs/aws-serverless-java-container</url>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.17.RELEASE</version>
    </parent>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-xray-recorder-sdk-core</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-xray-recorder-sdk-apache-http</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws.serverless</groupId>
            <artifactId>aws-serverless-java-container-spring</artifactId>
            <version>1.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>shaded-jar</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <version>2.3</version>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <artifactSet>
                                        <excludes>
                                            <exclude>org.apache.tomcat.embed:*</exclude>
                                        </excludes>
                                    </artifactSet>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>assembly-zip</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <!-- don't build a jar, we'll use the classes dir -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.1.1</version>
                        <executions>
                            <execution>
                                <id>default-jar</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- select and copy only runtime dependencies to a temporary lib folder -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>3.1.1</version>
                        <executions>
                            <execution>
                                <id>copy-dependencies</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>copy-dependencies</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}${file.separator}lib</outputDirectory>
                                    <includeScope>runtime</includeScope>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>zip-assembly</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <configuration>
                                    <finalName>${project.artifactId}-${project.version}</finalName>
                                    <descriptors>
                                        <descriptor>src${file.separator}assembly${file.separator}bin.xml</descriptor>
                                    </descriptors>
                                    <attach>false</attach>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

I created a function to just make a `GET` call using the xray instrumented HttpClient. Here's what that looks like:
```java
package cjr.sample;

import org.apache.commons.io.IOUtils;
import org.apache.http.HttpEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import com.amazonaws.xray.proxies.apache.http.HttpClientBuilder;
import org.apache.http.message.BasicHeader;

import java.io.IOException;
import java.io.InputStream;

public class GetSite {
    public static String getSite() throws IOException {
        CloseableHttpClient httpClient = HttpClientBuilder.create().build();
        HttpGet httpGet = new HttpGet("https://<example>");
        httpGet.addHeader(new BasicHeader("User-Agent", "test-app quick example"));
        httpGet.addHeader(new BasicHeader("Accept", "text/plain"));
        CloseableHttpResponse response = httpClient.execute(httpGet);
        try {
            HttpEntity entity = response.getEntity();
            InputStream inputStream = entity.getContent();
            return IOUtils.toString(inputStream);
        } finally {
            response.close();
        }
    }
}
```

I have a RestController as well which just calls `getSite()`. When I deploy the lambda function and Api Gateway stage, then hit my endpoint, I do see the http request included as part of the trace. I'm not seeing the error you are.

Is there anything different you're doing with your instrumentation logic?

**Comment by dhawalkp** [comment]
Hi, I used the similar code and I am also able to run on my local STS project fine. The only situation when I am getting this error is when I deploy this lambda fronted by API Gateway.
Seems like API Gateway, or proxy is injecting TraceID and Xray SDK is getting the traceid,segmentiD in the request in the first place and then couldnt create subsegment for outbound calls.
Below is the Response HTTP Headers:

{"X-Amzn-Trace-Id":"Root=1-5c50bc4e-c56b7bc630488628eb6414d3","Content-Type":"application/json;charset=UTF-8"}

Logs:

Execution log for request 5341e90c-2407-11e9-9d06-f56e81de3f32
Tue Jan 29 20:49:09 UTC 2019 : Starting execution for request: 5341e90c-2407-11e9-9d06-f56e81de3f32
Tue Jan 29 20:49:09 UTC 2019 : HTTP Method: GET, Resource Path: /USCISCaseStatusPoller/case/WAC100000000/status
Tue Jan 29 20:49:09 UTC 2019 : Method request path: {caseid=WAC100000000}
Tue Jan 29 20:49:09 UTC 2019 : Method request query string: {}
Tue Jan 29 20:49:09 UTC 2019 : Method request headers: {asd=asd}
Tue Jan 29 20:49:09 UTC 2019 : Method request body before transformations: 

Tue Jan 29 20:49:09 UTC 2019 : Endpoint request headers: {x-amzn-lambda-integration-tag=5341e90c-2407-11e9-9d06-f56e81de3f32, Authorization=************************************************************************************************************************************************************************************************************************************************************************************************************************338010, X-Amz-Date=20190129T204909Z, x-amzn-apigateway-api-id=uq0s0hncmi, X-Amz-Source-Arn=arn:aws:execute-api:us-west-2:414210492846:uq0s0hncmi/test-invoke-stage/GET/USCISCaseStatusPoller/case/{caseid}/status, Accept=application/json, User-Agent=AmazonAPIGateway_uq0s0hncmi, 
Tue Jan 29 20:49:09 UTC 2019 : Endpoint request body after transformations: {"resource":"/USCISCaseStatusPoller/case/{caseid}/status","path":"/USCISCaseStatusPoller/case/WAC100000000/status","httpMethod":"GET","headers":{"asd":"asd"},"multiValueHeaders":{"asd":["asd"]},"queryStringParameters":null,"multiValueQueryStringParameters":null,"pathParameters":{"caseid":"WAC100000000"},"stageVariables":null,"requestContext":{"path":"/USCISCaseStatusPoller/case/{caseid}/status","accountId":"414210492846","resourceId":"kwzw9n","stage":"test-invoke-stage","domainPrefix":"testPrefix","requestId":"5341e90c-2407-11e9-9d06-f56e81de3f32"
Tue Jan 29 20:49:22 UTC 2019 : Received response. Integration latency: 13776 ms
Tue Jan 29 20:49:22 UTC 2019 : Endpoint response body before transformations: {"statusCode":200,"multiValueHeaders":{"Content-Type":["application/json;charset=UTF-8"],"X-Amzn-Trace-Id":["Root=1-5c50bc4e-c56b7bc630488628eb6414d3;"]},"body":"{\"id\":\"WAC100000000\",\"status\":\"Could not retrieve\"}","isBase64Encoded":false}
Tue Jan 29 20:49:22 UTC 2019 : Endpoint response headers: {Date=Tue, 29 Jan 2019 20:49:22 GMT, Content-Type=application/json, Content-Length=247, Connection=keep-alive, x-amzn-RequestId=b440b44c-cf39-4465-be0c-f30d458bea7c, x-amzn-Remapped-Content-Length=0, X-Amz-Executed-Version=$LATEST, X-Amzn-Trace-Id=root=1-5c50bc45-74bd229ce2d280ffd04fead6;sampled=0}
Tue Jan 29 20:49:22 UTC 2019 : Method response body after transformations: {"id":"WAC100000000","status":"Could not retrieve"}
Tue Jan 29 20:49:22 UTC 2019 : Method response headers: {Content-Type=application/json;charset=UTF-8, X-Amzn-Trace-Id=Root=1-5c50bc4e-c56b7bc630488628eb6414d3}
Tue Jan 29 20:49:22 UTC 2019 : Successfully completed execution
Tue Jan 29 20:49:22 UTC 2019 : Method completed with status: 200

**Comment by dhawalkp** [comment]
Thanks @chrisradek for finding out the problem! The problem was the presence of  AWSXRayServletFilter in the filter chain of my spring boot causing the segment IDs to be created whereas in Lambdas, the filter must not be used for generating the tracing. I removed this filter and it works perfectly fine. I am closing this issue.
