### ISSUE TITLE
aws-xray-recorder-sdk-aws-sdk-instrumentor does not support SDKv2 clients

### ISSUE THREAD

**Issue by humanzz** [aws/aws-xray-sdk-java#68]
Hello,

Including **aws-xray-recorder-sdk-aws-sdk-instrumentor** adds the AWS SDK v1 global interceptor which activates Xray for all AWS SDKv1 clients.

I believe the counterpart to SDKv2 clients is missing. If I understand correctly, **/software/amazon/awssdk/global/handlers/execution.interceptors** should be included and list the required interceptor from **aws-xray-recorder-sdk-aws-sdk-v2**

**Comment by chrisradek** [comment]
@humanzz 
For automatic SDKv2 client instrumentation, you'll want to use the [aws-xray-recorder-sdk-aws-sdk-v2-instrumentor](https://mvnrepository.com/artifact/com.amazonaws/aws-xray-recorder-sdk-aws-sdk-v2-instrumentor) package.

**Comment by humanzz** [comment]
@chrisradek
Thanks for the prompt response and apologies for me missing the presence of this package.
Thanks.
