### ISSUE TITLE
Upgrade `com.fasterxml.jackson.core:jackson-databind` version

### ISSUE THREAD

**Issue by hervit0** [aws/aws-xray-sdk-java#70]
Hi team,

Please, would it be possible to upgrade this dependency: `com.fasterxml.jackson.core:jackson-databind`?

The latest version of the Jackson Databind library is [2.9.8](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind). Our vulnerability bot spotted that there was a high vulnerability with this library.

I would be more than happy to help upgrading this dependency via a pull request, but it looks like the dependencies are fetched remotely (I might be wrong).

Many thanks

**Comment by luluzhao** [comment]
@hervit0 Sorry for the late response. Feel free to send out PR when you have time and I will review it. Thanks.

**Comment by hervit0** [comment]
@luluzhao no worries at all, please where do you declare your dependencies for this project? I suspect the `pom.xml`, but can't see `com.fasterxml.jackson.core`, is that a dependency of a dependency for you?

Thanks

**Comment by luluzhao** [comment]
@hervit0, I double checked the code and yes, `com.fasterxml.jackson.core` is the dependency of `aws-sdk-java` which we are depending on. Currently, they are using version `2.6.7` for jackson.

**Comment by luluzhao** [comment]
Hi @hervit0 , I close this issue for now since it haven't been updated for about three weeks. Feel free to reopen it if you still have questions.
