### ISSUE TITLE
Flexible configuration of AWSServiceHandlerManifest

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-xray-sdk-java#71]
The `AWSServiceHandlerManifest` class configures which values from an SDK request are logged by the `TracingInterceptor`. However, there are only two ways to configure this:

- supply a URL to a single JSON file, which gets parsed by `TracingInterceptor`, or
- fall back to the default configuration (bundled with this library)

For example, currently there's no way to "append" configuration: if I want to modify the parameters logged for, say, calls to Lambda then I have to take a copy of the default file, modify it and bundle it myself. If the defaults change for other services at any point, my custom file will now be out of sync and the burden is on me to keep my config up to date.

It would be extremely useful to have more flexible configuration options for this. One possible design would be to:

- provide a flexible builder for `AWSServiceHandlerManifest`
  - move the logic to load the default configuration into here
  - add methods to load additional / custom JSON files
  - add methods to explicitly override parts of the configuration
- construct `TracingInterceptor` by passing an instance of `AWSServiceHandlerManifest` directly

I'm happy to have a stab at a PR for this if you think the design is reasonable?

**Comment by awssandra** [comment]
PR merged
