### ISSUE TITLE
Make TraceInterceptor.entityKey public

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-xray-sdk-java#72]
See https://github.com/aws/aws-sdk-java-v2/issues/1277 for an explanation of the underlying problem: `ExecutionAttribute` keys are deliberately compared / hashed by reference and not by name. 

I'd like to write some code which augments `TracingInterceptor` (e.g. by subclassing it) but I can't currently get hold of the trace entity from `ExecutionAttributes`.

One solution would be to make `entityKey` public so that other code could make use of it.

**Comment by luluzhao** [comment]
@ashleymercer thank you for contacting us regarding your use case. Would you mind sharing more details about why you want to inherit `TracingIntercepor` class and using the item inside the class.

**Comment by ashleymercer** [comment]
@luluzhao sure - in my case, I want to add some additional metadata to the trace segment for lambda invocation. For example, I might want to record the payload, but only under certain conditions (so I can't use the parameter whitelist, since that would enable payload logging for all requests).

**Comment by luluzhao** [comment]
@ashleymercer , actually you can provide your custom json file which contains the lambda metadata you want to add by using this method
```
    public TracingInterceptor(AWSXRayRecorder recorder, String accountId, URL parameterWhitelist) {
        this.recorder = recorder;
        this.accountId = accountId;
        initInterceptorManifest(parameterWhitelist);
}
```

By default, we provide a json [file](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-aws-sdk-v2/src/main/resources/com/amazonaws/xray/interceptors/DefaultOperationParameterWhitelist.json) which contains the aws metadata X-Ray SDK will record. However, you could provide your own json file to record more metadata. In this case, you don't need to manually get keys and inject more into it. Let me know if this method works for you or not. :)

**Comment by ashleymercer** [comment]
Hi @luluzhao - thanks for this. Yes, I understand that I can log the payload specifically by modifying the manifest (and you'll see I've already [raised an issue to make this more flexible](https://github.com/aws/aws-xray-sdk-java/issues/71).

However, this doesn't answer my specific questions:

- what if I only want to record the payload in _some_ cases (e.g. using some logic to test the request, and decide whether or not to trace the payload)?

- how can I attach other fields that are not part of the SDK (e.g. custom metadata that my code generates) to the `Entity` generated by `TracingInterceptor`?

On the second question: I'm currently generating a second "wrapper" trace entity around the actual lambda invocation, but this is clunky since I have to make sure to parse both trace segments and knit the data back together again. It would be much cleaner to put all the relevant data on a single segment.

**Comment by luluzhao** [comment]
@ashleymercer I agree with your concerns. I will merge your PR and thanks for your contribution.
