### ISSUE TITLE
`beginSegment()` should perform sampling if the caller haven't done any sampling decision

### ISSUE THREAD

**Issue by yogiraj07** [aws/aws-xray-sdk-java#74]
# Problem
The `beginSegment()` method doesn't perform sampling if the caller of this method hasn't done any sampling decision.
# Background
Currently sampling for a given incoming request is performed by [`shouldTrace()`](https://github.com/aws/aws-xray-sdk-java/blob/f227f20b70e33fe448cd31335170cf477f7054c0/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/sampling/CentralizedSamplingStrategy.java#L54). By default, this method starts pollers in the background to fetch sampling rules from the X-Ray console and sampling is performed based on fetched sampling rules.

# Usecase
Currently, `shouldTrace()` is only called by [AWSXRayServerFilter](https://github.com/aws/aws-xray-sdk-java/blob/eed8aa9f771bc69dee65409fdf4704874561bc86/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/javax/servlet/AWSXRayServletFilter.java#L251) middleware. In the scenario where a user doesn't want to use AWSXRayServletFilter middleware and instrument application using just `beginSegment()` and `endSegment()`, no sampling would be performed. This is due to limitation of [beginSegment](https://github.com/aws/aws-xray-sdk-java/blob/f893f6c123ce4958525d24681c1228887ce45256/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/AWSXRayRecorder.java#L337) not performing sampling, if the caller of this method has not performed sampling decision. As a result, all the segments are sampled and sampling rules configured through X-Ray console doesn't have any effect. 

# Proposed solution
[beginSegment](https://github.com/aws/aws-xray-sdk-java/blob/f893f6c123ce4958525d24681c1228887ce45256/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/AWSXRayRecorder.java#L337) should do sampling if the caller hasn't done any sampling.

# Reference 
AWS X-Ray SDK for [.NET/Core](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/AWSXRayRecorderImpl.cs#L156) has necessary implementation.

**Note** : 
1. This should be backwards compatible change.

**Comment by srprash** [comment]
Added new API for sampling.
https://github.com/aws/aws-xray-sdk-java/pull/196
