### ISSUE TITLE
Wrong inheritance of XRayInspector - does not compile

### ISSUE THREAD

**Issue by supercobra** [aws/aws-xray-sdk-java#8]
In the Spring example https://aws.amazon.com/blogs/devops/aspect-oriented-programming-for-aws-x-ray-using-spring/ `public class XRayInspector extends AbstractXRayInterceptor` and `@Override` method `protected Map<String, Map<String, Object>> generateMetadata` but there is no `generateMetadata` in the parent class.

Full code from link above:

```
@Aspect
@Component
public class XRayInspector extends AbstractXRayInterceptor {    
    @Override    
    protected Map<String, Map<String, Object>> generateMetadata(ProceedingJoinPoint proceedingJoinPoint, Subsegment subsegment) throws Exception {      
        return super.generateMetadata(proceedingJoinPoint, subsegment);    
    }    
  
  @Override    
  @Pointcut("@within(com.amazonaws.xray.spring.aop.XRayEnabled) && bean(*Controller)")    
  public void xrayEnabledClasses() {}
  
}
```

**Comment by haotianw465** [comment]
The SDK `v.1.3.1` was released which addresses this issue. Close now. Please re-open if you see additional issues regarding this release.
