### ISSUE TITLE
Spring Boot 2 Support for Database Tracing

### ISSUE THREAD

**Issue by RaphaelHerd** [aws/aws-xray-sdk-java#88]
Hi,

does anyone has an idea how to trace SQL queries (e.g. Postgres) in Spring Boot 2 as easy as in 1 by setting some kindof interceptor or so?

Thanks in advance

**Comment by PatricioMP** [comment]
In Spring boot 2, you need to exclude the default dependency database pool HikariCP from spring-boot-starter-data-jpa, then you need to add the old one tomcat-jdbc

**Comment by demetrio812** [comment]
Hello, so we can't have database tracing if we use HikariCP? Isn't HikariCP must faster than the Tomcat one?

**Comment by grobmeier** [comment]
HikariCP does not support tracing unfortunately. You would have to write your own agent or similar to make this work, or suggest that feature to the Hikari team

**Comment by shengxil** [comment]
In the latest X-Ray Java SDK we introduced a native SQL tracing decorator: https://github.com/aws/aws-xray-sdk-java/tree/master/aws-xray-recorder-sdk-sql

The library is JDBC independent and is verified with HikariCP. We don't have public document for it yet. Here is a basic instruction:

1. Update your X-Ray Java SDK to the latest version. If you are not using the entire SDK, add ```aws-xray-recorder-sdk-sql``` to your dependencies.

2. You can decorate your database datasource/connection/statement before to enable X-Ray tracing by
* ```dataSource = TracingDataSource.decorate(dataSource)``` 
* ```connection = TracingConnection.decorate(connection)```
* ```statement = TracingStatement.decorateStatement(statement)```
* ```preparedStatement = TracingStatement.decoratePreparedStatement(preparedStatement, sql)```
* ```callableStatement = TracingStatement.decorate CallableStatement(callableStatement, sql)```

The decorating should be performed before any query, and all queries after it will be traced with a subsegment and with metrics filled.

**Comment by willarmiros** [comment]
@Choi-JinHwan The X-Ray SDK Uses ThreadLocalStorage so you must manually propagate context between threads in multi-threaded environments. Please see this documentation for an example of passing a segment (or subsegment) to a new thread, and using the `run()` method to submit a runnable that will have X-Ray context available: https://docs.aws.amazon.com/xray/latest/devguide/scorekeep-workerthreads.html
