### ISSUE TITLE
Default constructor for HttpClientBuilder should be protected

### ISSUE THREAD

**Issue by garypgithub** [aws/aws-xray-sdk-java#89]
The Apache default (ie no-arg) constructor for HttpClientBuilder() is protected, forcing you to invoke the create() method in order to create an instance of the HttpClientBuilder().  However, no such default constructor is specified for the X-Ray HttpClientBuilder() so Java creates a default public constructor.  This allows you to create an instance of HttpClientBuilder with a null recorder resulting in an NPE down the road if you don't call the setRecorder method as most people wouldn't.

HttpClientBuilder() should explicitly specify a default no-arg constructor that is protected, making it impossible for a client to create a instance with a null value for recorder.  The protected constructor should also invoke super() so that values initialized in the Apache HttpClientBuilder constructor are also initialized here.

**Comment by chanchiem** [comment]
Thank you very much for reporting this issue! We will investigate this issue and get a fix out accordingly.

**Comment by chanchiem** [comment]
PR Out: #90
